spring:
  profiles:
    active: local
---

spring:
  profiles:
    group:
      "local": "local,common"
      "dev": "dev,common"
      "test": "common"
---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:postgresql://172.22.228.171:5432/petbuddy_local
    username: petbuddy
    password: "0694123"
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:postgresql://172.31.171.18:5432/petbuddy_local
    username: petbuddy
    password: "0694123"
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
---

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: "common"
  application:
    name: petbuddy
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
jwt:
  token:
    header: api_key
    issuer: petbuddy
    clientSecret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expirySeconds: 0
cloud:
  aws:
    s3:
      region: ap-northeast-2
      accessKey: AKIAICIRJ3XXHNYOOGLQ
      secretKey: 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
      url: https://s3.ap-northeast-2.amazonaws.com
      bucketName: prgrms-web-bjs
eventbus:
  asyncPoolCore: 1
  asyncPoolMax: 4
  asyncPoolQueue: 100
webpush:
  publicKey: BFJsnkDcKmsymlt5ZVUlIrGtqUxKVEiZ0iBRV3NKCFHrizInoT9FuA8MYESQVzbrTx4njj7lC3Iiz7K41dKUwGE
  privateKey: K0IOiuODucZ4Tu8WprpXVKwiPBvYYLe4cle4ZLdhPVY
server:
  port: 8101
